select * from customer limit 20
--1.what is the total revenue generated by male vs female customers.
select gender,sum(purchase_amount) as revenue
from customer
group by gender
--2.which customers used a discount but still spent more than the average than the average purshace amount?
select customer_id,purchase_amount
from customer
where discount_applied = 'Yes'
and purchase_amount >= (select avg(purchase_amount)from customer)
--3.which are the top 5 products with the higher average review rating
select item_purchased, round(avg(review_rating::numeric),2) as "average_product_rating"
from customer
group by item_purchased
order by average_product_rating desc
limit 5;
--4.compare the average purchase amount between standard and express shipping.
select shipping_type ,round(avg(purchase_amount::numeric),2) as "average_purchase"
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--5.do subscriber customers spend more? compare average spend and total revenue 
-- betweensubscribers and non-subscribers
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status

--6.which 5 products have highest percentage of purchase with discount applied?
select item_purchased,
round(sum(case when discount_applied ='Yes' then 1 else 0 end)*100 /count(*) , 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--7.segment customer into ew, returning, and loyal based on their total
-- number of previous purchases , and show the count of each segment.
with customer_type as (
 select customer_id,
 previous_purchases,
 case 
      when previous_purchases = 1 then 'New'
	  when previous_purchases between 2 and 10 then 'Returning'
	  else 'Loyal'
	  end as Customer_segment
  from customer)
  select customer_segment,count(*) as "Number of customer"
  from customer_type
  group by customer_segment

  --8.what are the top 3 most purchases product within each category?
  with item_counts as (
   select category,
   item_purchased,
   count(customer_id) as total_orders,
   row_number()over(partition by category order by count(customer_id)desc) as item_rank
   from customer
   group by category,item_purchased
  )
select item_rank, category,item_purchased,total_orders
from item_counts
where item_rank <= 3;

--9.are customers who are repeat buyers(more than 5 previous purchase) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--10.what is the revenue contribution of each age group
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
